org.gradle.daemon=false
org.gradle.debug=false

parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.03.23

minecraft_version=1.21.6
minecraft_version_range=[1.21.6,)
neo_version=21.6.0-beta
neo_version_range=[21.6.0-beta,)
loader_version_range=[4,)

mod_id=pigsteel
mod_name=Pigsteel
mod_license=Apache License Version 2.0
mod_version=7.1.0
mod_group_id=com.uraneptus.pigsteel
mod_authors=Uraneptus
mod_description=A mod that adds a nether counterpart to iron.
pack_format_number=34

